[pytest]
#log_format=%(asctime)s %(levelname)s %(message)s
#log_date_format=%Y-%m-%d %H:%M:%S

log_cli = true
log_level = INFO
log_format = %(asctime)s %(name)s: %(levelname)s %(message)s

addopts = 
	-s
	-v
	--html=Rest_rci_test_report.html
	--self-contained-html


python_files = 
	test_*.py
python_functions = 
	test_

